apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # Base64 encoded values - replace with your actual encoded secrets
  mongodb-uri: bW9uZ29kYjovL21vbmdvZGI6MjcwMTcvdGFza21hbmFnZXI=
  jwt-secret: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==