apiVersion: v1
kind: Service
metadata:
  name: task-manager-service
  labels:
    app: task-manager
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: task-manager